version: '3'
services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=jdbc
      - MYSQL_USER=jdbc
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3309:3306
volumes:
  db_data:
